"""add import_tasks table

Revision ID: 5e080f33afa6
Revises: cda1f670f1d6
Create Date: 2025-10-12 11:25:38.804881

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5e080f33afa6'
down_revision: Union[str, None] = 'cda1f670f1d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_table', sa.String(length=255), nullable=True),
    sa.Column('total_tables', sa.Integer(), nullable=True),
    sa.Column('total_keys', sa.Integer(), nullable=True),
    sa.Column('processed_keys', sa.Integer(), nullable=True),
    sa.Column('imported_keys', sa.Integer(), nullable=True),
    sa.Column('skipped_keys', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_tasks')
    # ### end Alembic commands ###
