"""add_key_count_cache

Revision ID: af1104902ab1
Revises: ed93e0135889
Create Date: 2025-08-27 18:36:15.001223

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'af1104902ab1'
down_revision: Union[str, None] = 'ed93e0135889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_count_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('count_value', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_column('keys_', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keys_', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('key_count_cache')
    # ### end Alembic commands ###
